spring.application.name=relay
server.port=${PORT:3000}

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/relay}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:relay}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:relay}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.type=com.zaxxer.hikari.HikariDataSource
spring.jpa.hibernate.ddl-auto=update

jwt.secret=${JWT_SECRET:Is-this-a-long-enough-secret-???-987654321}
jwt.expiry=${JWT_EXPIRY:3600000}

