export const STATUS = {
	TODO: 'TODO',
	IN_PROGRESS: 'IN_PROGRESS',
	IN_REVIEW: 'IN_REVIEW',
	DONE: 'DONE',
};

export const PRIORITIES = {
	LOW: 'LOW',
	MEDIUM: 'MEDIUM',
	HIGH: 'HIGH',
	URGENT: 'URGENT',
};
